--sql


 CREATE VIEW PRODUCTOS_PROVEDORES
 AS SELECT (e.NOMBRE,e.CLAVE,r.NOMBRE,r.CORREO)
 FROM PRODUCTOS e, PROVEDORES r
 WHERE e.ID_PROVEDORES = r.ID_PROVEDORES;
 
 CREATE VIEW PRODUCTOS_CATEGORIA
 AS SELECT (e.NOMBRE,e.CLAVE,r.NOMBRE,r.CORREO)
 FROM PRODUCTOS e, CATEGORIA r
 WHERE e.ID_CATEGORIAS = r.ID_CATEGORIAS;
